name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-targets
    - name: Clippy
      run: cargo clippy --no-deps --workspace --all-targets
    - name: Test
      run: cargo test --verbose
